# MULTIPLY TESTS


## ЗАДАНИЕ
Тестовым приложением является перемножитель двух целых чисел в промежутке от 0 до 100.
Веб-интерфейс расположен по адресу http://13.49.131.32/.
Прикладной компонент расположен по адресу  http://13.49.131.32:8080, принимает plain-http POST-запросы с 
двумя параметрами: first и second —  два числа, которые будут перемножены и возвращает произведение. 

```shell
#Пример запроса:
curl http://13.49.131.32:8080 -XPOST -H "Content-Length: 18" -d "first=42&second=54"

#Ответ :
2268
```

Необходимо провести автотестирование обоих компонентов.
Задачи:
* Написать автотесты для поиска значений, которые при перемножении дают неверный результат
* Проверить приложение на разных браузерах
* Проверить ошибки в интерфейсе и ошибки API
* Дополнительно:
  * Проверить максимально возможное количество одновременных подключений к серверу
  * Проверить доступность сервера на некотором непрерывном промежутке времени

Результатом выполнения задания является отчет о тестировании в формате pdf. Будет плюсом, если вы пришлете результат выполнения в виде проекта.


## ОПИСАНИЕ ВЫПОЛНЕНИЯ ЗАДАНИЯ
Используемый стек: python, py.test, requests, playwright

Тесты находятся в папке `tests`:
* `tests/api` - тесты на api метод перемножения
* `tests/ui` - тесты на интерфейс приложения и его взаимодействие с бекэндом

### API-тесты
Тесты на корректность работы сервиса и обработку ошибок содержатся в `tests/api/test_acceptance.py`

Тест на поиск значений, при которых перемножение может дать неверный результат содержится в `test_full_exhaustive_search.py`.
Этот тест выполняет полный перебор всех допустимых значений аргументов операции. Что на мой взгляд не совсем корректно,
но судя из постановки задачи, требовалось именно это. В целом проверять корректность перемножения было бы правильнее 
на уровне unit-тестов. 


### UI-тесты
Тесты на корректность работы сервиса и обработку ошибок в UI содержатся в `tests/ui/test_acceptance.py`.
Так как в приложении валидация входных данных сделана и на бекэнде и на фронте, та часть валидации которая
относится к фронту проверяется в ui-тестах.


## ЗАПУСК ТЕСТОВ

### Опции запуска тестов:
- `--BASE_URL` - позволяет передать базовую часть адреса сервиса (по-умолчанию тесты будут запускаться 
на стенде `http://13.49.131.32`, если нужно на другом стенде, то укажите его адрес через данную опцию)
- `--ALLURE` - сохранять результаты прохождении автотестов в формате allure
- `--headed` (только для ui-тестов) - без передачи этого флага тесты запускаются в headless-режиме. 
- `--browser` (только для ui-тестов) - позволяет выбрать на каком браузере запукать тесты, 
доступные значения `chromium` (по умолчанию), `firefox`, `webkit`. 



### Запуск в  Docker

1. Выполнить сборку образа
```sh
cd calculator_tests
docker build -t calculator_tests .
```

2. Запустить api-тесты в контейнере
```sh
# Запустить api-тесты с выводом результатов тестирования в консоли
docker run -it --rm calculator_tests /usr/local/bin/py.test -v -l tests/api/test_acceptance.py

# ИЛИ можно запустить api-тесты с возможность получения результатов тестирования в allure-отчете
# Для этого нужно запустить контейнер
docker run -it --rm -p 5005:5005 calculator_tests
# В нем выполнить команду запуска api-тестов
pytest -v -l tests/api/test_acceptance.py --ALLURE
# После завершения прогона запустить генерацию allure-отчета
allure serve -p 5005 logs/allure-results/

# Отчет будет доступен по http://0.0.0.0:5005/index.html
```

3. Запустить ui-тесты в контейнере
```sh
# Запустить ui-тесты с выводом результатов тестирования в консоли (на браузере chrome, 
# для запуска на других браузерах указать браузер в опции `--browser`)
docker run -it --rm calculator_tests /usr/local/bin/py.test -v -l tests/ui --browser=chromium

# ИЛИ можно запустить ui-тесты с возможность получения результатов тестирования в allure-отчете
# Для этого нужно запустить контейнер
docker run -it --rm -p 5005:5005 calculator_tests
# В нем выполнить команду запуска api-тестов 
pytest -v -l tests/ui --BASE_URL=http://13.49.131.32 --ALLURE --browser=chromium
# После завершения прогона запустить генерацию allure-отчета
allure serve -p 5005 logs/allure-results/

# Отчет будет доступен по http://0.0.0.0:5005/index.html
```

###  Локальный запуск

У Вас уже должен быть установлен Python не ниже 3.8
2. Установить зависимости проекта
```sh
cd calculator_tests
pip install --upgrade -r requirements.txt
```

2. Запустить тесты коммандой:

```sh
# Запустить api-тесты
pytest -v -l tests/api/test_acceptance.py

# Запустить ui-тесты
pytest -v -l tests/ui --browser=chromium
```

Если путь до py.test не прописан в PATH, то его следует указать в комманде запуска (узнать его можно командой "which py.test"):
```sh
#Пример:
/usr/local/bin/py.test -v -l tests
```

Для возможности генерить allure-отчет из результатов тестирования нужно:
- установить [allure-commandline](https://docs.qameta.io/allure/#_commandline)
- запускать тесты с опцией `--ALLURE`
- после их прохождения перейти в папку проекта и выполнить команду `allure serve logs/allure-results/`, отчет будет
доступен по ссылке отображаемой в коносли.

По-умолчанию тесты запускаются в headless-режиме (без GUI). Если вы хотите наблюдать как тесты отрабатывают в 
UI-браузера, то нужно запускать тесты с опцией `--headed`
```sh
pytest -v -l tests/ui --browser=chromium --headed
```



## ОШИБКИ И ЗАМЕЧАНИЯ

### Ошибка 1
Api выдает результат перемножения для целых чисел выходящих за диапазон от 0 до 100.
- для значений меньше 0 в любом из аргументов метод выдает результат перемножения.
- для значений больше 100 в любом из аргументов метод выдает результат перемножения
- 
Пример:
```shell
# Запрос
curl -X 'POST' -H 'Accept: */*' -d 'first=101&second=1' 'http://13.49.131.32:8080/'

#Ответ:
101

# Ожидалось что метод вернет сообщение об ошибке, так как по требованиям должен принимать только целые числа в
# промежутке от 0 до 100
```

### Ошибка 2
Приложение не работает на браузере Firefiox. Кнопка "Multiply" не кликабельна. Проверял на разных версиях Firefox, 
например на версии 0.99.1 на osX.

### Замечания
1. Api отвечат со status_code=200, даже на те запросы в которые возвращают сообщение об ошибке из-за того что 
переданы невалидные данные. 
```shell
# Запрос
curl -i http://13.49.131.32:8080 -XPOST -H "Content-Length: 18" -d "first=aaa&second=54"

# Ответ
HTTP/1.0 200 OK
Server: BaseHTTP/0.6 Python/3.7.10
Date: Tue, 03 May 2022 09:54:54 GMT
access-control-allow-origin: *

Something went wrong :(%
```
Рекомендуется возвращать '400 Bad Request'

2. Api в случае ошибки валидации входных параметров возвращает не информативное сообщение "Something went wrong :(". 
Рекоммендуется возвращать сообщение из которого будет понятна причина ошибки